### ISSUE TITLE
✨ Add to the prompt to only send the same link once

### ISSUE THREAD

**Issue by Hona** [SSWConsulting/SSW.Rules.GPT#106]
Cc: @MattParkerDev @jackreimers @calumjs @adamcogan 

Hi 
  
### Pain

Some responses will spam the same link multiple times which feels a bit clunky 

From Adam's talk :)

### Suggested Solution

Add it to the prompt, something like

'Don't send the same URL twice. I'd you need to reference it, use the short title of the rule'

### Tasks

- [ ] ...
- [ ] ...

### Screenshots

Thanks!

**Comment by jackreimers** [comment]
@Hona can you give some examples of prompts where this occured?

**Comment by Hona** [comment]
I skimmed the talk - here is from his live demo: https://youtu.be/imlPFRNtSJI?t=4553
