### ISSUE TITLE
🐛 GPT4 API Key does not work

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rules.GPT#111]
Cc:

Hi 

### Describe the Bug

I am unable to use my own GPT4 API key with RulesGPT

### To Reproduce
1. Go to https://platform.openai.com/account/api-keys
2. Click on `+ Create new secret key`
3. Copy the key to the clipboard
4. Go to https://rulesgpt.ssw.com.au/
5. Click on the cog icon and select API Key
6. Select Use my own API key
7. Paste the key and save
8. See error "Invalid API key"

### Expected Behavior

The key should work

### Tasks
- [ ] Investigate
- [ ] Fix

### Acceptance Criteria

 * When a user follows the steps described above, they are able to use RulesGPT with their own API key
 * The steps mentioned above (or the correct steps, if these are wrong) are available via a Help button within the RulesGPT add API key dialog
 * More descriptive error messages are displayed when the OpenAI endpoint returns a specfic error, ie. insufficient quota

### More Information

Might be worth noting that in OpenAI I can see records of the key being used.
![image](https://github.com/SSWConsulting/SSW.Rules.GPT/assets/19944129/98e49a00-3b4f-4402-acae-ec7fd05e8bb6)
**Figure: OpenAI has a 'last used' entry for this key, so it appears that RulesGPT is attempting to use it**

Thanks!

**Comment by jackreimers** [comment]
@matt-goldman could you open the network tab before you click save on the key and check the response from the completions endpoint after clicking save? That should tell us the cause of the failure.

For example my personal account has no credit for the API so I get an invalid key error but it's actually insufficient quota:
![image](https://github.com/SSWConsulting/SSW.Rules.GPT/assets/10693364/c8652271-9816-4180-aad6-191a2d913734)
**Figure: 429 error from insufficient OpenAI API quota**

I'll update the acceptance criteria to add more descriptive validation error messages as part of this issue

**Comment by matt-goldman** [comment]
@jackreimers done - I can see I get a 404 with a message saying that I do not have access to GPT4, along with a link to more info. The link is this one: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4

According to this I should have GPT4 access - that's another issue I can take up with OpenAI.

Suggestion would be to surface the error that comes back via the UI. Also still suggest updating the instructions.

```json
{
    "error": {
        "message": "The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}
```
