### ISSUE TITLE
👷 Prod and staging deploying at the same time

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Rules.GPT#113]
Cc: @wicksipedia @matt-goldman @adamcogan 

Hi @jackreimers 
  
### Pain
Both Production and Staging are deploy code from main at the same time. This means you cant push something to staging without it going to production.

### Potential Solutions

1. Ephemeral environments - each PR builds its own environment (recommended)
2. Make prod and staging build from different branches e.g. have a `release/x` branch for prod
3. Delete staging - If this problem hasn't been noticed before, staging probably isn't required

```[tasklist]
### Tasks
- [ ] Implement ephemeral environments (see SSW.Website as an example)
``` 

### Acceptance Criteria
1. Each PR deploys to a new slot for testing
2. Merging the PR deletes that slot and deploys code to main

**Comment by jackreimers** [comment]
@bradystroud implementing ephemeral environments will require upgrading our app service plan.
Do we want to add this additional cost given the relatively low volume of PRs in this repo compared to SSW.Website?

**Comment by bradystroud** [comment]
I am open to alternatives, I'd talk to tech lead for this project.
Also, increasing cost should be a PO decision.

**Comment by jackreimers** [comment]
As per my conversation with @calumjs we not going to implement ephemeral environments and instead have an automatic deployment to staging and manual deployment to production

**Comment by matt-goldman** [comment]
> Also, increasing cost should be a PO decision.

As there is no standard for this, it should be a PO anyway.

Also looks like we need a standard for this.

**Comment by matt-goldman** [comment]
> As per my conversation with @calumjs we not going to implement ephemeral environments and instead have an automatic deployment to staging and manual deployment to production

This is consistent with what we're doing for our other products (except the website.

**Comment by bradystroud** [comment]
Hey @jackreimers I see this is done but there is no done video or any evidence.

> Also looks like we need a standard for this.
Do we have one?
