### ISSUE TITLE
♻️ Use System Theme as Default

### ISSUE THREAD

**Issue by Hona** [SSWConsulting/SSW.Rules.GPT#134]
Make the default theme the 'Use System Theme' & not light mode

**Comment by jackreimers** [comment]
@Hona the default being light mode was at Adams request.
If you set the preference in the app it will save to your local storage

**Comment by Hona** [comment]
Damn, yep I updated it for my own local storage :)

**Comment by jackreimers** [comment]
Closing - no action required

**Comment by bradystroud** [comment]
Hey @jackreimers GitHub has a button for when we close stuff and there was no work done

<img width="1017" alt="image" src="https://github.com/SSWConsulting/SSW.Rules.GPT/assets/38869720/693f3fbd-a416-448c-8066-15105e65c1d0">
