### ISSUE TITLE
🐛 BUG - KV not updating connection string 

### ISSUE THREAD

**Issue by JackDevAU** [SSWConsulting/SSW.Rules.GPT#157]
Cc: @pierssinclairssw @MattParkerDev @adamcogan @jackreimers 

Hi Team,

### Describe the Bug

The KeyVault reference that is linking to the database connection string isn't working correctly. 

A post on potentially the same issue:
https://www.reddit.com/r/AZURE/comments/17jcvel/key_vault_secret_reference_resolves_to_empty/

### To Reproduce
1. Go to RulesGPT Stage | Api 
2. Click on Configuration 
3. Go to Rules GPT Stage | KV
4. Update Connection string  
5. Restart Api
6. See that the connection string hasn't been updated

### Expected Behavior

On restart of the app, the connection string is pull from the KV reference and used. 

### Tasks
- [ ] Investigate
- [ ] Fix

Thanks!

**Comment by MattParkerDev** [comment]
Maybe related: https://stackoverflow.com/questions/75698178/azure-web-app-loses-permissions-on-a-keyvault-secret-when-a-new-secret-version-i

**Comment by jackreimers** [comment]
@MattParkerDev has this been resolved?

**Comment by MattParkerDev** [comment]
@jackreimers yep, I don't think this was the issue. Closing.
