### ISSUE TITLE
UI - Add ChatGPT logo to home page

### ISSUE THREAD

**Issue by MattParkerDev** [SSWConsulting/SSW.Rules.GPT#63]
@BrookJeynes @adamcogan 

Add the ChatGPT Logo beside the RulesGPT title

**Comment by BrookJeynes** [comment]
(Checked by @MattParkerDev)

Hey @MattParkerDev, it always helps to add a bit more detail to PBI items :)

As per my conversation with @adamcogan and @MattParkerDev, you will be adding the ChatGPT logo beside the RulesGPT title. This will add more branding and awareness that this is a GPT AI product.

![image](https://github.com/SSWConsulting/SSW.Rules.GPT/assets/25432120/0e993012-5e0d-4111-89b2-fc4d5c046ca9)
**Figure: Mock-up of new design with GPT Logo**
