### ISSUE TITLE
🐛 👤 Cancel Request covers output

### ISSUE THREAD

**Issue by Hona** [SSWConsulting/SSW.Rules.GPT#67]
Cc: @MattParkerDev 

**Hi RulesGPT team,**

### Describe the Bug

There is a small UX problem where the cancel request button will cover output

![image](https://github.com/SSWConsulting/SSW.Rules.GPT/assets/10430890/94651825-7600-440e-89fb-71010168cece)

### Tasks
- [ ] Investigate
- [ ] Fix

### Environment
 - Device: [e.g. iPhone 12]
 - Browser: [e.g. chrome, safari]

### Screenshots

Thanks!

**Comment by MattParkerDev** [comment]
Duplicate of #47

**Comment by jackreimers** [comment]
Resolved by #47
