### ISSUE TITLE
✨Add SSW.IdentityServer

### ISSUE THREAD

**Issue by jackreimers** [SSWConsulting/SSW.Rules.GPT#98]
Cc: @adamcogan @calumjs @matt-goldman @sethdailyssw
  
### Pain

Currently we are unable to track who is using RulesGPT.

### Suggested Solution

Implement SSW.IdentityServer in a similar way to SSW Rewards to allow users to sign in.

### Tasks

- [ ] Implement SSW.IdentityServer 
- [ ] Build login dialog

### Acceptance Criteria

Users can sign in to receive access to gpt-4.
Signed in users details such as name and email are tracked in App Insights.
Anonymous users are prompted to sign in.

Thanks!

**Comment by bradystroud** [comment]
This isn't going to make more people use RulesGPT (it will probably reduce usage) 

I would focus on fixing the reasons people dont use it e.g. #48 #78

**Comment by jackreimers** [comment]
@bradystroud I don't think it will reduce usage as we are not locking anything except SSWs gpt-4 key behind sign in at this stage although I agree that it probably won't help increase it.

Given that this was requested by Adam I'm going to prioritise it. Perhaps there should be more of a discussion about its implementation?

**Comment by sethdailyssw** [comment]
To me #48 sounds like the most important one, followed by this one. I guess it doesn't really matter if this gets done first, though.

**Comment by calumjs** [comment]
I agree with Brady & Seth, #48 is becoming more important over time as the snapshot of rules we are operating on recedes into the distant past.
